stages:
  - build

build:
  stage: build
  image: docker:1.13.1-dind
  tags:
    - docker
    - dind
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t registry.nocsi.org/triton-portal:latest -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
    - docker push registry.nocsi.org/triton-portal
